#!/bin/bash
iptables -A IN_STAT -m state --state NEW -m geoip --source-country AF
iptables -A IN_STAT -m state --state NEW -m geoip --source-country AX
iptables -A IN_STAT -m state --state NEW -m geoip --source-country AL
iptables -A IN_STAT -m state --state NEW -m geoip --source-country DZ
iptables -A IN_STAT -m state --state NEW -m geoip --source-country AS
iptables -A IN_STAT -m state --state NEW -m geoip --source-country AD
iptables -A IN_STAT -m state --state NEW -m geoip --source-country AO
iptables -A IN_STAT -m state --state NEW -m geoip --source-country AI
iptables -A IN_STAT -m state --state NEW -m geoip --source-country AQ
iptables -A IN_STAT -m state --state NEW -m geoip --source-country AG
iptables -A IN_STAT -m state --state NEW -m geoip --source-country AR
iptables -A IN_STAT -m state --state NEW -m geoip --source-country AM
iptables -A IN_STAT -m state --state NEW -m geoip --source-country AW
iptables -A IN_STAT -m state --state NEW -m geoip --source-country AU
iptables -A IN_STAT -m state --state NEW -m geoip --source-country AT
iptables -A IN_STAT -m state --state NEW -m geoip --source-country AZ
iptables -A IN_STAT -m state --state NEW -m geoip --source-country BS
iptables -A IN_STAT -m state --state NEW -m geoip --source-country BH
iptables -A IN_STAT -m state --state NEW -m geoip --source-country BD
iptables -A IN_STAT -m state --state NEW -m geoip --source-country BB
iptables -A IN_STAT -m state --state NEW -m geoip --source-country BY
iptables -A IN_STAT -m state --state NEW -m geoip --source-country BE
iptables -A IN_STAT -m state --state NEW -m geoip --source-country BZ
iptables -A IN_STAT -m state --state NEW -m geoip --source-country BJ
iptables -A IN_STAT -m state --state NEW -m geoip --source-country BM
iptables -A IN_STAT -m state --state NEW -m geoip --source-country BT
iptables -A IN_STAT -m state --state NEW -m geoip --source-country BO
iptables -A IN_STAT -m state --state NEW -m geoip --source-country BQ
iptables -A IN_STAT -m state --state NEW -m geoip --source-country BA
iptables -A IN_STAT -m state --state NEW -m geoip --source-country BW
iptables -A IN_STAT -m state --state NEW -m geoip --source-country BV
iptables -A IN_STAT -m state --state NEW -m geoip --source-country BR
iptables -A IN_STAT -m state --state NEW -m geoip --source-country IO
iptables -A IN_STAT -m state --state NEW -m geoip --source-country BN
iptables -A IN_STAT -m state --state NEW -m geoip --source-country BG
iptables -A IN_STAT -m state --state NEW -m geoip --source-country BF
iptables -A IN_STAT -m state --state NEW -m geoip --source-country BI
iptables -A IN_STAT -m state --state NEW -m geoip --source-country KH
iptables -A IN_STAT -m state --state NEW -m geoip --source-country CM
iptables -A IN_STAT -m state --state NEW -m geoip --source-country CA
iptables -A IN_STAT -m state --state NEW -m geoip --source-country CV
iptables -A IN_STAT -m state --state NEW -m geoip --source-country KY
iptables -A IN_STAT -m state --state NEW -m geoip --source-country CF
iptables -A IN_STAT -m state --state NEW -m geoip --source-country TD
iptables -A IN_STAT -m state --state NEW -m geoip --source-country CL
iptables -A IN_STAT -m state --state NEW -m geoip --source-country CN
iptables -A IN_STAT -m state --state NEW -m geoip --source-country CX
iptables -A IN_STAT -m state --state NEW -m geoip --source-country CC
iptables -A IN_STAT -m state --state NEW -m geoip --source-country CO
iptables -A IN_STAT -m state --state NEW -m geoip --source-country KM
iptables -A IN_STAT -m state --state NEW -m geoip --source-country CG
iptables -A IN_STAT -m state --state NEW -m geoip --source-country CD
iptables -A IN_STAT -m state --state NEW -m geoip --source-country CK
iptables -A IN_STAT -m state --state NEW -m geoip --source-country CR
iptables -A IN_STAT -m state --state NEW -m geoip --source-country CI
iptables -A IN_STAT -m state --state NEW -m geoip --source-country HR
iptables -A IN_STAT -m state --state NEW -m geoip --source-country CU
iptables -A IN_STAT -m state --state NEW -m geoip --source-country CW
iptables -A IN_STAT -m state --state NEW -m geoip --source-country CY
iptables -A IN_STAT -m state --state NEW -m geoip --source-country CZ
iptables -A IN_STAT -m state --state NEW -m geoip --source-country DK
iptables -A IN_STAT -m state --state NEW -m geoip --source-country DJ
iptables -A IN_STAT -m state --state NEW -m geoip --source-country DM
iptables -A IN_STAT -m state --state NEW -m geoip --source-country DO
iptables -A IN_STAT -m state --state NEW -m geoip --source-country EC
iptables -A IN_STAT -m state --state NEW -m geoip --source-country EG
iptables -A IN_STAT -m state --state NEW -m geoip --source-country SV
iptables -A IN_STAT -m state --state NEW -m geoip --source-country GQ
iptables -A IN_STAT -m state --state NEW -m geoip --source-country ER
iptables -A IN_STAT -m state --state NEW -m geoip --source-country EE
iptables -A IN_STAT -m state --state NEW -m geoip --source-country ET
iptables -A IN_STAT -m state --state NEW -m geoip --source-country FK
iptables -A IN_STAT -m state --state NEW -m geoip --source-country FO
iptables -A IN_STAT -m state --state NEW -m geoip --source-country FJ
iptables -A IN_STAT -m state --state NEW -m geoip --source-country FI
iptables -A IN_STAT -m state --state NEW -m geoip --source-country FR
iptables -A IN_STAT -m state --state NEW -m geoip --source-country GF
iptables -A IN_STAT -m state --state NEW -m geoip --source-country PF
iptables -A IN_STAT -m state --state NEW -m geoip --source-country TF
iptables -A IN_STAT -m state --state NEW -m geoip --source-country GA
iptables -A IN_STAT -m state --state NEW -m geoip --source-country GM
iptables -A IN_STAT -m state --state NEW -m geoip --source-country GE
iptables -A IN_STAT -m state --state NEW -m geoip --source-country DE
iptables -A IN_STAT -m state --state NEW -m geoip --source-country GH
iptables -A IN_STAT -m state --state NEW -m geoip --source-country GI
iptables -A IN_STAT -m state --state NEW -m geoip --source-country GR
iptables -A IN_STAT -m state --state NEW -m geoip --source-country GL
iptables -A IN_STAT -m state --state NEW -m geoip --source-country GD
iptables -A IN_STAT -m state --state NEW -m geoip --source-country GP
iptables -A IN_STAT -m state --state NEW -m geoip --source-country GU
iptables -A IN_STAT -m state --state NEW -m geoip --source-country GT
iptables -A IN_STAT -m state --state NEW -m geoip --source-country GG
iptables -A IN_STAT -m state --state NEW -m geoip --source-country GN
iptables -A IN_STAT -m state --state NEW -m geoip --source-country GW
iptables -A IN_STAT -m state --state NEW -m geoip --source-country GY
iptables -A IN_STAT -m state --state NEW -m geoip --source-country HT
iptables -A IN_STAT -m state --state NEW -m geoip --source-country HM
iptables -A IN_STAT -m state --state NEW -m geoip --source-country VA
iptables -A IN_STAT -m state --state NEW -m geoip --source-country HN
iptables -A IN_STAT -m state --state NEW -m geoip --source-country HK
iptables -A IN_STAT -m state --state NEW -m geoip --source-country HU
iptables -A IN_STAT -m state --state NEW -m geoip --source-country IS
iptables -A IN_STAT -m state --state NEW -m geoip --source-country IN
iptables -A IN_STAT -m state --state NEW -m geoip --source-country ID
iptables -A IN_STAT -m state --state NEW -m geoip --source-country IR
iptables -A IN_STAT -m state --state NEW -m geoip --source-country IQ
iptables -A IN_STAT -m state --state NEW -m geoip --source-country IE
iptables -A IN_STAT -m state --state NEW -m geoip --source-country IM
iptables -A IN_STAT -m state --state NEW -m geoip --source-country IL
iptables -A IN_STAT -m state --state NEW -m geoip --source-country IT
iptables -A IN_STAT -m state --state NEW -m geoip --source-country JM
iptables -A IN_STAT -m state --state NEW -m geoip --source-country JP
iptables -A IN_STAT -m state --state NEW -m geoip --source-country JE
iptables -A IN_STAT -m state --state NEW -m geoip --source-country JO
iptables -A IN_STAT -m state --state NEW -m geoip --source-country KZ
iptables -A IN_STAT -m state --state NEW -m geoip --source-country KE
iptables -A IN_STAT -m state --state NEW -m geoip --source-country KI
iptables -A IN_STAT -m state --state NEW -m geoip --source-country KP
iptables -A IN_STAT -m state --state NEW -m geoip --source-country KR
iptables -A IN_STAT -m state --state NEW -m geoip --source-country KW
iptables -A IN_STAT -m state --state NEW -m geoip --source-country KG
iptables -A IN_STAT -m state --state NEW -m geoip --source-country LA
iptables -A IN_STAT -m state --state NEW -m geoip --source-country LV
iptables -A IN_STAT -m state --state NEW -m geoip --source-country LB
iptables -A IN_STAT -m state --state NEW -m geoip --source-country LS
iptables -A IN_STAT -m state --state NEW -m geoip --source-country LR
iptables -A IN_STAT -m state --state NEW -m geoip --source-country LY
iptables -A IN_STAT -m state --state NEW -m geoip --source-country LI
iptables -A IN_STAT -m state --state NEW -m geoip --source-country LT
iptables -A IN_STAT -m state --state NEW -m geoip --source-country LU
iptables -A IN_STAT -m state --state NEW -m geoip --source-country MO
iptables -A IN_STAT -m state --state NEW -m geoip --source-country MK
iptables -A IN_STAT -m state --state NEW -m geoip --source-country MG
iptables -A IN_STAT -m state --state NEW -m geoip --source-country MW
iptables -A IN_STAT -m state --state NEW -m geoip --source-country MY
iptables -A IN_STAT -m state --state NEW -m geoip --source-country MV
iptables -A IN_STAT -m state --state NEW -m geoip --source-country ML
iptables -A IN_STAT -m state --state NEW -m geoip --source-country MT
iptables -A IN_STAT -m state --state NEW -m geoip --source-country MH
iptables -A IN_STAT -m state --state NEW -m geoip --source-country MQ
iptables -A IN_STAT -m state --state NEW -m geoip --source-country MR
iptables -A IN_STAT -m state --state NEW -m geoip --source-country MU
iptables -A IN_STAT -m state --state NEW -m geoip --source-country YT
iptables -A IN_STAT -m state --state NEW -m geoip --source-country MX
iptables -A IN_STAT -m state --state NEW -m geoip --source-country FM
iptables -A IN_STAT -m state --state NEW -m geoip --source-country MD
iptables -A IN_STAT -m state --state NEW -m geoip --source-country MC
iptables -A IN_STAT -m state --state NEW -m geoip --source-country MN
iptables -A IN_STAT -m state --state NEW -m geoip --source-country ME
iptables -A IN_STAT -m state --state NEW -m geoip --source-country MS
iptables -A IN_STAT -m state --state NEW -m geoip --source-country MA
iptables -A IN_STAT -m state --state NEW -m geoip --source-country MZ
iptables -A IN_STAT -m state --state NEW -m geoip --source-country MM
iptables -A IN_STAT -m state --state NEW -m geoip --source-country NA
iptables -A IN_STAT -m state --state NEW -m geoip --source-country NR
iptables -A IN_STAT -m state --state NEW -m geoip --source-country NP
iptables -A IN_STAT -m state --state NEW -m geoip --source-country NL
iptables -A IN_STAT -m state --state NEW -m geoip --source-country NC
iptables -A IN_STAT -m state --state NEW -m geoip --source-country NZ
iptables -A IN_STAT -m state --state NEW -m geoip --source-country NI
iptables -A IN_STAT -m state --state NEW -m geoip --source-country NE
iptables -A IN_STAT -m state --state NEW -m geoip --source-country NG
iptables -A IN_STAT -m state --state NEW -m geoip --source-country NU
iptables -A IN_STAT -m state --state NEW -m geoip --source-country NF
iptables -A IN_STAT -m state --state NEW -m geoip --source-country MP
iptables -A IN_STAT -m state --state NEW -m geoip --source-country NO
iptables -A IN_STAT -m state --state NEW -m geoip --source-country OM
iptables -A IN_STAT -m state --state NEW -m geoip --source-country PK
iptables -A IN_STAT -m state --state NEW -m geoip --source-country PW
iptables -A IN_STAT -m state --state NEW -m geoip --source-country PS
iptables -A IN_STAT -m state --state NEW -m geoip --source-country PA
iptables -A IN_STAT -m state --state NEW -m geoip --source-country PG
iptables -A IN_STAT -m state --state NEW -m geoip --source-country PY
iptables -A IN_STAT -m state --state NEW -m geoip --source-country PE
iptables -A IN_STAT -m state --state NEW -m geoip --source-country PH
iptables -A IN_STAT -m state --state NEW -m geoip --source-country PN
iptables -A IN_STAT -m state --state NEW -m geoip --source-country PL
iptables -A IN_STAT -m state --state NEW -m geoip --source-country PT
iptables -A IN_STAT -m state --state NEW -m geoip --source-country PR
iptables -A IN_STAT -m state --state NEW -m geoip --source-country QA
iptables -A IN_STAT -m state --state NEW -m geoip --source-country RE
iptables -A IN_STAT -m state --state NEW -m geoip --source-country RO
iptables -A IN_STAT -m state --state NEW -m geoip --source-country RU
iptables -A IN_STAT -m state --state NEW -m geoip --source-country RW
iptables -A IN_STAT -m state --state NEW -m geoip --source-country BL
iptables -A IN_STAT -m state --state NEW -m geoip --source-country SH
iptables -A IN_STAT -m state --state NEW -m geoip --source-country KN
iptables -A IN_STAT -m state --state NEW -m geoip --source-country LC
iptables -A IN_STAT -m state --state NEW -m geoip --source-country MF
iptables -A IN_STAT -m state --state NEW -m geoip --source-country PM
iptables -A IN_STAT -m state --state NEW -m geoip --source-country VC
iptables -A IN_STAT -m state --state NEW -m geoip --source-country WS
iptables -A IN_STAT -m state --state NEW -m geoip --source-country SM
iptables -A IN_STAT -m state --state NEW -m geoip --source-country ST
iptables -A IN_STAT -m state --state NEW -m geoip --source-country SA
iptables -A IN_STAT -m state --state NEW -m geoip --source-country SN
iptables -A IN_STAT -m state --state NEW -m geoip --source-country RS
iptables -A IN_STAT -m state --state NEW -m geoip --source-country SC
iptables -A IN_STAT -m state --state NEW -m geoip --source-country SL
iptables -A IN_STAT -m state --state NEW -m geoip --source-country SG
iptables -A IN_STAT -m state --state NEW -m geoip --source-country SX
iptables -A IN_STAT -m state --state NEW -m geoip --source-country SK
iptables -A IN_STAT -m state --state NEW -m geoip --source-country SI
iptables -A IN_STAT -m state --state NEW -m geoip --source-country SB
iptables -A IN_STAT -m state --state NEW -m geoip --source-country SO
iptables -A IN_STAT -m state --state NEW -m geoip --source-country ZA
iptables -A IN_STAT -m state --state NEW -m geoip --source-country GS
iptables -A IN_STAT -m state --state NEW -m geoip --source-country SS
iptables -A IN_STAT -m state --state NEW -m geoip --source-country ES
iptables -A IN_STAT -m state --state NEW -m geoip --source-country LK
iptables -A IN_STAT -m state --state NEW -m geoip --source-country SD
iptables -A IN_STAT -m state --state NEW -m geoip --source-country SR
iptables -A IN_STAT -m state --state NEW -m geoip --source-country SJ
iptables -A IN_STAT -m state --state NEW -m geoip --source-country SZ
iptables -A IN_STAT -m state --state NEW -m geoip --source-country SE
iptables -A IN_STAT -m state --state NEW -m geoip --source-country CH
iptables -A IN_STAT -m state --state NEW -m geoip --source-country SY
iptables -A IN_STAT -m state --state NEW -m geoip --source-country TW
iptables -A IN_STAT -m state --state NEW -m geoip --source-country TJ
iptables -A IN_STAT -m state --state NEW -m geoip --source-country TZ
iptables -A IN_STAT -m state --state NEW -m geoip --source-country TH
iptables -A IN_STAT -m state --state NEW -m geoip --source-country TL
iptables -A IN_STAT -m state --state NEW -m geoip --source-country TG
iptables -A IN_STAT -m state --state NEW -m geoip --source-country TK
iptables -A IN_STAT -m state --state NEW -m geoip --source-country TO
iptables -A IN_STAT -m state --state NEW -m geoip --source-country TT
iptables -A IN_STAT -m state --state NEW -m geoip --source-country TN
iptables -A IN_STAT -m state --state NEW -m geoip --source-country TR
iptables -A IN_STAT -m state --state NEW -m geoip --source-country TM
iptables -A IN_STAT -m state --state NEW -m geoip --source-country TC
iptables -A IN_STAT -m state --state NEW -m geoip --source-country TV
iptables -A IN_STAT -m state --state NEW -m geoip --source-country UG
iptables -A IN_STAT -m state --state NEW -m geoip --source-country UA
iptables -A IN_STAT -m state --state NEW -m geoip --source-country AE
iptables -A IN_STAT -m state --state NEW -m geoip --source-country GB
iptables -A IN_STAT -m state --state NEW -m geoip --source-country US
iptables -A IN_STAT -m state --state NEW -m geoip --source-country UM
iptables -A IN_STAT -m state --state NEW -m geoip --source-country UY
iptables -A IN_STAT -m state --state NEW -m geoip --source-country UZ
iptables -A IN_STAT -m state --state NEW -m geoip --source-country VU
iptables -A IN_STAT -m state --state NEW -m geoip --source-country VE
iptables -A IN_STAT -m state --state NEW -m geoip --source-country VN
iptables -A IN_STAT -m state --state NEW -m geoip --source-country VG
iptables -A IN_STAT -m state --state NEW -m geoip --source-country VI
iptables -A IN_STAT -m state --state NEW -m geoip --source-country WF
iptables -A IN_STAT -m state --state NEW -m geoip --source-country EH
iptables -A IN_STAT -m state --state NEW -m geoip --source-country YE
iptables -A IN_STAT -m state --state NEW -m geoip --source-country ZM
iptables -A IN_STAT -m state --state NEW -m geoip --source-country ZW
